// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUmNkx0FkjjyPBeA7upznETIa_KCAlMB4',
    appId: '1:567660714831:web:25e3e87e13792db6a7c33a',
    messagingSenderId: '567660714831',
    projectId: 'testproject-622fc',
    authDomain: 'testproject-622fc.firebaseapp.com',
    storageBucket: 'testproject-622fc.appspot.com',
    measurementId: 'G-X6NNCDDJJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAS9Bd0OSz7TUJAN79x4H0yugTApBBgK8',
    appId: '1:567660714831:android:501075c9c1c5bc56a7c33a',
    messagingSenderId: '567660714831',
    projectId: 'testproject-622fc',
    storageBucket: 'testproject-622fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeiuz9rY9026higPn4KoNU4VhjDjePvZk',
    appId: '1:567660714831:ios:ede11079ca4386b2a7c33a',
    messagingSenderId: '567660714831',
    projectId: 'testproject-622fc',
    storageBucket: 'testproject-622fc.appspot.com',
    iosClientId: '567660714831-g70ttvg9t767go7u3s30v0ag43nlrca4.apps.googleusercontent.com',
    iosBundleId: 'com.aaqwise.testproject',
  );
}
